# Generated by Django 3.0.5 on 2020-07-14 10:39

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200712_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to=notes.models.content_img_name),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
