# Generated by Django 3.0.5 on 2020-07-15 07:11

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200714_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=notes.models.content_file_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
