# Generated by Django 3.0.5 on 2020-07-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0008_auto_20200718_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='duser',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
