# Generated by Django 3.0.5 on 2020-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_posts_bku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_reck',
            name='bid',
            field=models.ImageField(default='default_book.jpg', max_length=311, upload_to=''),
        ),
    ]
